import React, { useRef, useEffect, useState } from 'react';
import QrScanner from 'react-qr-scanner';

interface QRCodeScannerProps {
  onScan: (data: string | null) => void;
  onError?: (err: any) => void;
}

export const QRCodeScanner: React.FC<QRCodeScannerProps> = ({ onScan, onError }) => {
  const [scanning, setScanning] = useState(false);
  const [scanResult, setScanResult] = useState<string | null>(null);
  const [delay] = useState(300);

  const handleScan = (data: string | null) => {
    if (data) {
      setScanResult(data);
      setScanning(false);
      onScan(data);
    }
  };

  const handleError = (err: any) => {
    if (onError) {
      onError(err);
    }
  };

  return (
    <div>
      <button
        className="bg-cyan-600 text-white px-4 py-2 rounded mb-2"
        onClick={() => setScanning(!scanning)}
      >
        {scanning ? 'Stop Scanning' : 'Scan QR Code'}
      </button>
      {scanning && (
        <div className="p-2 bg-white rounded shadow-lg inline-block">
          <QrScanner
            delay={delay}
            onError={handleError}
            onScan={handleScan}
            style={{ width: 220 }}
          />
        </div>
      )}
      {scanResult && (
        <div className="mt-2 text-xs text-gray-700">Scanned: {scanResult}</div>
      )}
    </div>
  );
};
// Pseudocode generated by codewrx.ai
