import React, { useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';

interface QRCodeTourProps {
  tourId: string;
  tourData: any;
  onScan?: (tourId: string) => void;
}

export const QRCodeTour: React.FC<QRCodeTourProps> = ({ tourId, tourData, onScan }) => {
  const [showQR, setShowQR] = useState(false);
  const qrValue = JSON.stringify({ tourId, tourData });

  return (
    <div>
      <button
        className="bg-cyan-600 text-white px-4 py-2 rounded mb-2"
        onClick={() => setShowQR(!showQR)}
      >
        {showQR ? 'Hide QR Code' : 'Share Tour (QR)'}
      </button>
      {showQR && (
        <div className="p-4 bg-white rounded shadow-lg inline-block">
          <QRCodeSVG value={qrValue} size={180} />
          <div className="mt-2 text-xs text-gray-700">Scan to join this tour</div>
        </div>
      )}
      {/* QR code scanning logic would go here (e.g. using a webcam library) */}
    </div>
  );
};
// Pseudocode generated by codewrx.ai
