import { 
  Palette, Map, Ruler, Building2, 
  Zap, Brain, MessageSquare, Cloud, Droplets, Wind, Volume2, 
  Car, Sun, Bot, Mic, Activity, Zap as EnergyIcon, DollarSign, 
  Users, MessageCircle, Share2, Headphones, Smartphone, Volume, Zap as HapticIcon, 
  MapPin, Camera, Settings, Eye, FileText, 
  Search, Star, Gift, Scale, Play, 
  Move, Zap as TeleportIcon, Fish, Eye as MultiSensoryIcon, 
  Volume1, Info, Folder, Globe, Lightbulb, 
  Shield, Fan, Route, Hash, Loader, 
  Mic as PresentationIcon, User, Zap as QuantumIcon, 
  Split, Map as TourIcon, Calculator, 
  MapPin as GeoAreaIcon, RefreshCw, Camera as CameraViewsIcon, 
  Users as CollabIcon, Layers 
} from 'lucide-react';

import type { Feature } from '../components/UI/ControlPanel/FeatureButton';

export const featureCategories: Record<string, Feature[]> = {
  'Core Features': [
    {
      id: 'showMaterialEditor',
      name: 'Material Editor',
      icon: Palette,
      category: 'Core Features',
      enabled: false,
      hotkey: 'M',
      description: 'Edit materials and textures for meshes.',
      performanceImpact: 1,
      dependencies: [],
      isEssential: true
    },
    {
      id: 'showMinimap',
      name: 'Minimap',
      icon: Map,
      category: 'Core Features',
      enabled: false,
      hotkey: 'I',
      description: 'Show a 2D minimap of the 3D scene.',
      performanceImpact: 1,
      dependencies: [],
      isEssential: true
    },
    {
      id: 'showMeasurementTool',
      name: 'Measurement Tool',
      icon: Ruler,
      category: 'Core Features',
      enabled: false,
      hotkey: 'T',
      description: 'Measure distances and dimensions in the scene.',
      performanceImpact: 1,
      dependencies: [],
      isEssential: true
    },
    {
      id: 'showBIMIntegration',
      name: 'BIM Integration',
      icon: Building2,
      category: 'Core Features',
      enabled: false,
      hotkey: 'B',
      description: 'Building Information Modeling tools (clash detection, cost analysis, energy analysis).',
      performanceImpact: 1,
      dependencies: [],
      isEssential: true
    }
  ],
  'Important Features': [
    {
      id: 'showAutoFurnish',
      name: 'Auto Furnish',
      icon: Zap,
      category: 'Important Features',
      enabled: false,
      hotkey: 'A',
      description: 'Automatic furniture placement using AI.',
      performanceImpact: 2,
      dependencies: ['showAICoDesigner'],
      isEssential: false
    },
    {
      id: 'showAICoDesigner',
      name: 'AI Co-Designer',
      icon: Brain,
      category: 'Important Features',
      enabled: false,
      hotkey: 'C',
      description: 'AI collaborative design with gesture detection.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showAnnotations',
      name: 'Annotations',
      icon: MessageSquare,
      category: 'Important Features',
      enabled: false,
      hotkey: 'N',
      description: 'Add annotations to the scene.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showWeather',
      name: 'Weather',
      icon: Cloud,
      category: 'Important Features',
      enabled: false,
      hotkey: 'W',
      description: 'Weather simulation and effects.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showFloodSimulation',
      name: 'Flood',
      icon: Droplets,
      category: 'Important Features',
      enabled: false,
      hotkey: 'F',
      description: 'Flood simulation with water mesh.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showWind',
      name: 'Wind',
      icon: Wind,
      category: 'Important Features',
      enabled: false,
      hotkey: 'D',
      description: 'Wind simulation effects.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showNoise',
      name: 'Noise',
      icon: Volume2,
      category: 'Important Features',
      enabled: false,
      hotkey: 'O',
      description: 'Noise simulation with visualization spheres.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showTraffic',
      name: 'Traffic',
      icon: Car,
      category: 'Important Features',
      enabled: false,
      hotkey: 'R',
      description: 'Traffic simulation.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showSunlightAnalysis',
      name: 'Shadow Analysis',
      icon: Sun,
      category: 'Important Features',
      enabled: false,
      hotkey: 'S',
      description: 'Shadow analysis (sunlight analysis).',
      performanceImpact: 2,
      dependencies: ['showBIMIntegration'],
      isEssential: false
    },
    {
      id: 'showAIAdvisor',
      name: 'AI Advisor',
      icon: Bot,
      category: 'Important Features',
      enabled: false,
      hotkey: 'V',
      description: 'AI-powered design advisor.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showVoiceAssistant',
      name: 'Voice Assistant',
      icon: Mic,
      category: 'Important Features',
      enabled: false,
      hotkey: 'U',
      description: 'Voice-controlled assistant.',
      performanceImpact: 2,
      dependencies: ['showAIAdvisor'],
      isEssential: false
    },
    {
      id: 'showErgonomic',
      name: 'Ergonomic',
      icon: Activity,
      category: 'Important Features',
      enabled: false,
      hotkey: 'E',
      description: 'Ergonomic analysis.',
      performanceImpact: 2,
      dependencies: ['showBIMIntegration'],
      isEssential: false
    },
    {
      id: 'showEnergy',
      name: 'Energy',
      icon: EnergyIcon,
      category: 'Important Features',
      enabled: false,
      hotkey: 'G',
      description: 'Energy efficiency analysis.',
      performanceImpact: 2,
      dependencies: ['showBIMIntegration'],
      isEssential: false
    },
    {
      id: 'showCost',
      name: 'Cost',
      icon: DollarSign,
      category: 'Important Features',
      enabled: false,
      hotkey: 'Q',
      description: 'Cost estimation.',
      performanceImpact: 2,
      dependencies: ['showBIMIntegration'],
      isEssential: false
    },
    {
      id: 'showMultiUser',
      name: 'Multi User',
      icon: Users,
      category: 'Important Features',
      enabled: false,
      hotkey: 'U',
      description: 'Multi-user collaboration.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showChat',
      name: 'Chat',
      icon: MessageCircle,
      category: 'Important Features',
      enabled: false,
      hotkey: 'H',
      description: 'Real-time chat.',
      performanceImpact: 2,
      dependencies: ['showMultiUser'],
      isEssential: false
    },
    {
      id: 'showSharing',
      name: 'Sharing',
      icon: Share2,
      category: 'Important Features',
      enabled: false,
      hotkey: 'X',
      description: 'Share workspace.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showVR',
      name: 'VR',
      icon: Headphones,
      category: 'Important Features',
      enabled: false,
      hotkey: 'V',
      description: 'Virtual reality mode.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showAR',
      name: 'AR',
      icon: Smartphone,
      category: 'Important Features',
      enabled: false,
      hotkey: 'A',
      description: 'Augmented reality mode.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showSpatialAudio',
      name: 'Spatial Audio',
      icon: Volume,
      category: 'Important Features',
      enabled: false,
      hotkey: 'P',
      description: '3D spatial audio.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showHaptic',
      name: 'Haptic',
      icon: HapticIcon,
      category: 'Important Features',
      enabled: false,
      hotkey: 'H',
      description: 'Haptic feedback.',
      performanceImpact: 2,
      dependencies: ['showVR'],
      isEssential: false
    },
    {
      id: 'showGeoLocation',
      name: 'Geo Location',
      icon: MapPin,
      category: 'Important Features',
      enabled: false,
      hotkey: 'L',
      description: 'GPS-based location services.',
      performanceImpact: 2,
      dependencies: [],
      isEssential: false
    }
  ],
  'Nice-to-Have Features': [
    {
      id: 'showScanAnimal',
      name: 'Scan Animal',
      icon: Search,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'AI-powered animal scanning and detection.',
      performanceImpact: 3,
      dependencies: ['showAICoDesigner'],
      isEssential: false
    },
    {
      id: 'showMoodScene',
      name: 'Mood Scene',
      icon: Star,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Interactive lighting mood scenes.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showSeasonalDecor',
      name: 'Seasonal Decor',
      icon: Gift,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Seasonal decoration management.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showARScale',
      name: 'AR Scale',
      icon: Scale,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Augmented reality scaling tools.',
      performanceImpact: 3,
      dependencies: ['showAR'],
      isEssential: false
    },
    {
      id: 'showScenario',
      name: 'Scenario',
      icon: Play,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Interactive scenario presentation.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showMovementControlChecker',
      name: 'Movement Control Checker',
      icon: Move,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Check movement controls.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showTeleportManager',
      name: 'Teleport Manager',
      icon: TeleportIcon,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Teleport navigation.',
      performanceImpact: 3,
      dependencies: ['showVR'],
      isEssential: false
    },
    {
      id: 'showSwimMode',
      name: 'Swim Mode',
      icon: Fish,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Underwater exploration mode.',
      performanceImpact: 3,
      dependencies: ['showFloodSimulation'],
      isEssential: false
    },
    {
      id: 'showMultiSensoryPreview',
      name: 'Multi Sensory Preview',
      icon: MultiSensoryIcon,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Multi-sensory preview.',
      performanceImpact: 3,
      dependencies: ['showSpatialAudio', 'showHaptic'],
      isEssential: false
    },
    {
      id: 'showNoiseSimulation',
      name: 'Noise Simulation',
      icon: Volume1,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Noise simulation.',
      performanceImpact: 3,
      dependencies: ['showNoise'],
      isEssential: false
    },
    {
      id: 'showPropertyInspector',
      name: 'Property Inspector',
      icon: Info,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Inspect properties.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showSceneBrowser',
      name: 'Scene Browser',
      icon: Folder,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Browse scenes.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showSiteContextGenerator',
      name: 'Site Context Generator',
      icon: Globe,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Generate site context.',
      performanceImpact: 3,
      dependencies: ['showGeoLocation'],
      isEssential: false
    },
    {
      id: 'showSmartAlternatives',
      name: 'Smart Alternatives',
      icon: Lightbulb,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Smart alternatives.',
      performanceImpact: 3,
      dependencies: ['showAIAdvisor'],
      isEssential: false
    },
    {
      id: 'showSoundPrivacySimulation',
      name: 'Sound Privacy Simulation',
      icon: Shield,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Sound privacy simulation.',
      performanceImpact: 3,
      dependencies: ['showNoise'],
      isEssential: false
    },
    {
      id: 'showSustainabilityCompliancePanel',
      name: 'Sustainability Compliance Panel',
      icon: Shield,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Sustainability compliance.',
      performanceImpact: 3,
      dependencies: ['showEnergy'],
      isEssential: false
    },
    {
      id: 'showWindTunnelSimulation',
      name: 'Wind Tunnel Simulation',
      icon: Fan,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Wind tunnel simulation with particles.',
      performanceImpact: 3,
      dependencies: ['showWind'],
      isEssential: false
    },
    {
      id: 'showPathTracing',
      name: 'Path Tracing',
      icon: Route,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Path tracing.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showPHashIntegration',
      name: 'PHash Integration',
      icon: Hash,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Perceptual hashing.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showProgressiveLoader',
      name: 'Progressive Loader',
      icon: Loader,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Progressive loading.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showPresentationManager',
      name: 'Presentation Manager',
      icon: PresentationIcon,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Presentation management.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showPresenterMode',
      name: 'Presenter Mode',
      icon: User,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Presenter mode.',
      performanceImpact: 3,
      dependencies: ['showPresentationManager'],
      isEssential: false
    },
    {
      id: 'showQuantumSimulationInterface',
      name: 'Quantum Simulation Interface',
      icon: QuantumIcon,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Quantum simulation.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showBeforeAfter',
      name: 'Before After',
      icon: Split,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Compare before and after states.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showComparativeTour',
      name: 'Comparative Tour',
      icon: TourIcon,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Side-by-side comparative tours.',
      performanceImpact: 3,
      dependencies: ['showBeforeAfter'],
      isEssential: false
    },
    {
      id: 'showROICalculator',
      name: 'ROI Calculator',
      icon: Calculator,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'ROI calculations.',
      performanceImpact: 3,
      dependencies: ['showCost'],
      isEssential: false
    },
    {
      id: 'showGeoWorkspaceArea',
      name: 'Geo Workspace Area',
      icon: GeoAreaIcon,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Define workspace area with geo-coordinates.',
      performanceImpact: 3,
      dependencies: ['showGeoLocation'],
      isEssential: false
    },
    {
      id: 'showGeoSync',
      name: 'Geo Sync',
      icon: RefreshCw,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Synchronize with geo-location data.',
      performanceImpact: 3,
      dependencies: ['showGeoLocation'],
      isEssential: false
    },
    {
      id: 'showCameraViews',
      name: 'Camera Views',
      icon: CameraViewsIcon,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Camera views.',
      performanceImpact: 3,
      dependencies: [],
      isEssential: false
    },
    {
      id: 'showCollabManager',
      name: 'Collab Manager',
      icon: CollabIcon,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Collaboration management.',
      performanceImpact: 3,
      dependencies: ['showMultiUser'],
      isEssential: false
    },
    {
      id: 'showComprehensiveSimulation',
      name: 'Comprehensive Simulation',
      icon: Layers,
      category: 'Nice-to-Have Features',
      enabled: false,
      description: 'Comprehensive simulation.',
      performanceImpact: 3,
      dependencies: ['showBIMIntegration', 'showEnergy', 'showWind'],
      isEssential: false
    }
  ]
};
